POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dpbWllcyIsImlkIjoiNjJmMjkxOTA2NTFlODMyYjAxZTk0M2E1IiwiaWF0IjoxNjYwMDY0MTU5fQ.gpHze9AmXvovT1nOygA9zwOkVZoKcMTMDq1tBV-MxxU

{
    "title": "Peliblogi",
    "author": "Pelimies",
    "url": "pelit.fi",
    "likes": 7
}